### ISSUE TITLE
The declared "on_model" function is missing

### ISSUE THREAD

**Issue by pavelmaksimov** [boardpack/reforms#20]
There is an example with import in the documentation

```python 
from reforms import Reforms, on_model
```

I didn't find the "on_model "function

**Comment by dukkee** [comment]
Hi @pavelmaksimov Sorry for the so late answer, yes, you are right, the correct import is:
```python
from reforms.contrib.fastapi import on_model
```

**Comment by yvechang** [comment]
ImportError: cannot import name 'on_model' from 'reforms.contrib.fastapi'

**Comment by dukkee** [comment]
Hi @yvechang sorry, this is a typo in the docs... Helper has a `from_model` name. I'll fix this mistake

**Comment by yvechang** [comment]
Hi @dukkee, I got your message. Thanks a lot!
